
version: '3.8'

services:

  redis:
    image: redis:6.2
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - custom
    command: redis-server --appendonly yes --requirepass 123456789

  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    hostname: redis_commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379:0:123456789
      - HTTP_USER=redis
      - HTTP_PASSWORD=123456789
    ports:
      - "16379:8081"
    networks:
      - custom
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=123456789
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - custom

  minio:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    container_name: minio
    hostname: minio
    restart: unless-stopped
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=123456789
    ports:
      - "9000:9000"
    volumes:
      - /data/minio:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - custom

  nginx:
    image: nginx:1.18.0
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/mime.types:/etc/nginx/mime.types
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/log:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
    depends_on:
      - minio
    networks:
      - custom

  nacos:
    image: nacos/nacos-server:1.0.0
    container_name: nacos
    hostname: nacos
    restart: unless-stopped
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=nacos
    ports:
      - "8848:8848"
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
      - nacos_data:/home/nacos/data
    networks:
      - custom



networks:
  default:
  custom:
    driver: bridge

volumes:
  redis_data:
  rabbitmq_data:
  nacos_data:



